### ISSUE TITLE
Test failures with new_rvalue_from_ptr on i686

### ISSUE THREAD

**Issue by davidmalcolm** [davidmalcolm/pygccjit#5]
A couple of tests are failing on i686:
```
test_dereference (test.JitTests) ... ERROR
test_imported_function (test.JitTests) ... ok
test_opaque_struct (test.JitTests) ... ok
test_rvalue_from_ptr (test.JitTests) ... ERROR
test_square (test.JitTests) ... ok
test_sum_of_squares (test.JitTests) ... ok
======================================================================
ERROR: test_dereference (test.JitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-gccjit-0.1-3.fc19/tests/test.py", line 225, in test_dereference
    nonnull_ptr = ctxt.new_rvalue_from_ptr(type_, id(self))
  File "gccjit.pyx", line 206, in gccjit._gccjit.Context.new_rvalue_from_ptr (gccjit/gccjit.c:4477)
OverflowError: Python int too large to convert to C long
======================================================================
ERROR: test_rvalue_from_ptr (test.JitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-gccjit-0.1-3.fc19/tests/test.py", line 219, in test_rvalue_from_ptr
    nonnull_ptr = ctxt.new_rvalue_from_ptr(type_, id(self))
  File "gccjit.pyx", line 206, in gccjit._gccjit.Context.new_rvalue_from_ptr (gccjit/gccjit.c:4477)
OverflowError: Python int too large to convert to C long
----------------------------------------------------------------------
Ran 6 tests in 0.243s
FAILED (errors=2)
```

**Comment by davidmalcolm** [comment]
Should be fixed in 541d3a6e1dbd9016d62c9069b2a4d1cad8fd9875
